name: ci

on:
  workflow_call:
    outputs:
      package_version:
        description: "Package version"
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.version }}
      
    steps:
      - id: version
        run: echo "1.1.1=version" >> $ GITHUB_OUTPUT 
